apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.version: 1.2.0
  labels:
    io.kompose.service: postgres
  name: postgres
spec:
  replicas: 1
  template:
    metadata:
      labels:
        io.kompose.service: postgres
    spec:
      containers:
      - image: postgres:9.5.6-alpine
        name: postgres
        ports:
          - containerPort: 5432

